# Generated by Django 5.0.2 on 2024-05-02 15:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('calorias', models.FloatField(default=0)),
                ('proteinas', models.FloatField(default=0)),
                ('carbohidratos', models.FloatField(default=0)),
                ('grasas', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10)),
                ('objetivo', models.CharField(blank=True, max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dieta', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=10)),
                ('proposito', models.CharField(blank=True, max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('duracion', models.DurationField(default=datetime.timedelta(days=30))),
            ],
        ),
        migrations.CreateModel(
            name='MedidasCorporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('fecha_medicion', models.DateField(blank=True, null=True)),
                ('porcentaje_grasa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('importe', models.FloatField(default=0)),
                ('pago', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10)),
                ('zona_muscular', models.CharField(blank=True, max_length=10)),
                ('equipo_necesario', models.CharField(blank=True, max_length=10)),
                ('foto', models.ImageField(blank=True, default='athletes/athlete_default_photo.png', null=True, upload_to='athletes/pics')),
                ('tipo_de_ejercicio', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=10)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios', to='core.area')),
            ],
        ),
        migrations.CreateModel(
            name='Gramaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('alimentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gramaje', to='core.alimentos')),
                ('dietas', models.ManyToManyField(related_name='gramajes', to='core.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField(default=0)),
                ('peso_alcanzado', models.FloatField(default=0)),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.ejercicios')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_rutina', models.DurationField(blank=True, default=datetime.timedelta(days=30))),
                ('lista_ejercicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutina', to='core.ejercicios')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_entrenamiento', models.DateField(null=True)),
                ('dias_descanso', models.DateField(null=True)),
                ('duracion_ejercicio', models.DurationField(null=True)),
                ('repeticiones', models.IntegerField(default=0)),
                ('tiempo_descanso', models.DurationField(null=True)),
                ('cantidad_series', models.IntegerField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('dieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='core.dieta')),
                ('ejercicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='core.ejercicios')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='core.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_entrenador', models.BooleanField(default=False)),
                ('nombre', models.CharField(blank=True, max_length=10)),
                ('edad', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=30)),
                ('foto', models.ImageField(blank=True, default='static/img/fotos/cliente.png', null=True, upload_to='static/img/fotos/')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.cliente')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.actividad')),
                ('medidas_corporales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.medidascorporales')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.suscripcion')),
            ],
        ),
    ]
