# Generated by Django 5.0.2 on 2024-05-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramaje',
            name='dietas',
            field=models.ManyToManyField(related_name='gramaje', to='core.dieta'),
        ),
    ]
