# Generated by Django 5.0.2 on 2024-05-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gramaje_dietas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alimentos',
            new_name='Alimento',
        ),
    ]
