# Generated by Django 5.0.2 on 2024-03-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alimentos_especie_alimentos_nombre_area_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
