# Generated by Django 5.0.2 on 2024-03-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cantidad_series',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actividad',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='actividad',
            name='repeticiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='cliente.png', null=True, upload_to='media/foto/'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='foto',
            field=models.ImageField(blank=True, default='athletes/athlete_default_photo.png', null=True, upload_to='athletes/pics'),
        ),
        migrations.AddField(
            model_name='gramaje',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medidascorporales',
            name='altura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medidascorporales',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='records',
            name='peso_alcanzado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='records',
            name='repeticiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='importe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='pago',
            field=models.FloatField(default=0),
        ),
    ]
