# Generated by Django 5.0.2 on 2024-05-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_alimentos_alimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedidasCorporales',
            new_name='MedidaCorporal',
        ),
    ]
