# Generated by Django 5.0.2 on 2024-10-09 22:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_medidascorporales_medidacorporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='dieta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='core.dieta'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ejercicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='core.ejercicios'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividad', to='core.rutina'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='direccion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='objetivo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='entrenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='static/img/fotos/cliente.png', null=True, upload_to='static/img/fotos/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='medidas_corporales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.medidacorporal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.actividad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='suscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.suscripcion'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='descripcion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='fecha_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='nombre_dieta',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='proposito',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios', to='core.area'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='descripcion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='equipo_necesario',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='foto',
            field=models.ImageField(default='athletes/athlete_default_photo.png', null=True, upload_to='athletes/pics'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='tipo_de_ejercicio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='zona_muscular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gramaje',
            name='alimentos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gramaje', to='core.alimento'),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='fecha_medicion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='porcentaje_grasa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='ejercicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.ejercicios'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='duracion_rutina',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='lista_ejercicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutina', to='core.ejercicios'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inscripcion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
