# Generated by Django 5.0.2 on 2024-03-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actividad_cantidad_series_actividad_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
