# Generated by Django 5.0.2 on 2024-03-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_suscripcion_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='especie',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='calorias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='carbohidratos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='grasas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='proteinas',
            field=models.FloatField(default=0),
        ),
    ]
