# Generated by Django 5.0.2 on 2024-10-18 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_actividad_dieta_alter_actividad_ejercicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='dieta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dieta'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ejercicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ejercicios'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rutina'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='entrenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='medidas_corporales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.medidacorporal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.actividad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='suscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.suscripcion'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.area'),
        ),
        migrations.AlterField(
            model_name='gramaje',
            name='alimentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alimento'),
        ),
        migrations.RemoveField(
            model_name='gramaje',
            name='dietas',
        ),
        migrations.AlterField(
            model_name='records',
            name='ejercicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ejercicios'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='lista_ejercicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ejercicios'),
        ),
        migrations.AddField(
            model_name='gramaje',
            name='dietas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dieta'),
            preserve_default=False,
        ),
    ]
