# Generated by Django 5.0.2 on 2024-03-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_alimentos_especie_alimentos_calorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
