# Generated by Django 5.0.2 on 2024-10-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_actividad_dieta_alter_actividad_ejercicios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='dias_descanso',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='dias_entrenamiento',
        ),
        migrations.AddField(
            model_name='rutina',
            name='dias_descanso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='dias_entrenamiento',
            field=models.DateField(null=True),
        ),
    ]
