# Generated by Django 5.0.2 on 2024-10-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_actividad_dias_descanso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(default='hipertrofia'),
            preserve_default=False,
        ),
    ]
