# Generated by Django 5.0.2 on 2024-03-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_alimentos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramaje',
            name='alimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gramaje', to='core.alimentos'),
        ),
    ]
