# Generated by Django 5.0.2 on 2024-03-26 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_gramaje_alimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_entrenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='core.actividad'),
        ),
        migrations.AlterField(
            model_name='gramaje',
            name='alimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gramaje', to='core.alimentos'),
        ),
    ]
