# Generated by Django 5.0.2 on 2024-10-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rutina_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='lista_ejercicios',
        ),
    ]
