# Generated by Django 5.0.2 on 2024-10-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_actividad_dieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='dias_descanso',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dias_entrenamiento',
            field=models.CharField(default='lunes, miercoles, viernes'),
            preserve_default=False,
        ),
    ]
