# Generated by Django 5.0.2 on 2024-03-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_es_entrenador_alter_cliente_rutina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidascorporales',
            name='fecha_medicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medidascorporales',
            name='porcentaje_grasa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
