# Generated by Django 5.0.2 on 2024-10-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_rutina_dias_descanso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicios',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.area'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='equipo_necesario',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='foto',
            field=models.ImageField(blank=True, default='athletes/athlete_default_photo.png', null=True, upload_to='athletes/pics'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='tipo_de_ejercicio',
            field=models.CharField(blank=True, choices=[('fuera', 'fuerza'), ('cardio', 'cardio'), ('elasticidad', 'elasticidad')]),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='zona_muscular',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
