# Generated by Django 5.0.2 on 2024-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medidascorporales_fecha_medicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gramaje',
            name='alimentos',
        ),
        migrations.AddField(
            model_name='gramaje',
            name='alimentos',
            field=models.ManyToManyField(to='core.alimentos'),
        ),
    ]
