# Generated by Django 5.0.2 on 2024-10-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ejercicios_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='direccion',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='objetivo',
            field=models.CharField(blank=True),
        ),
    ]
