# Generated by Django 5.0.2 on 2024-10-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_area_descripcion_alter_area_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicios',
            name='descripcion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='equipo_necesario',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='nombre',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='zona_muscular',
            field=models.CharField(blank=True),
        ),
    ]
