# Generated by Django 5.0.2 on 2024-10-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ejercicios_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='duracion_ejercicio',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
