# Generated by Django 5.0.2 on 2024-10-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_actividad_duracion_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='duracion_ejercicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_descanso',
            field=models.TimeField(null=True),
        ),
    ]
