# Generated by Django 5.0.2 on 2024-10-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ejercicios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicios',
            name='foto',
            field=models.ImageField(blank=True, default='gym/fotos/cliente.png', null=True, upload_to='gym/img'),
        ),
    ]
