# Generated by Django 5.0.2 on 2024-11-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ejercicios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='cantidad_series',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='peso',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='repeticiones',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_descanso',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
