# Generated by Django 5.0.2 on 2024-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_actividad_cantidad_series_alter_actividad_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='duracion_ejercicio',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_descanso',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
