# Generated by Django 5.0.2 on 2024-11-11 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_actividad_duracion_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='duracion_ejercicio',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_descanso',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
