# Generated by Django 5.0.2 on 2024-11-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_actividad_duracion_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ejercicios',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, to='core.ejercicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='rutina',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.PROTECT, to='core.rutina'),
            preserve_default=False,
        ),
    ]
