# Generated by Django 5.0.2 on 2024-11-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_actividad_ejercicios_alter_actividad_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='gramaje',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras'), ('g', 'Gramos')], default='g', max_length=2),
        ),
    ]
