# Generated by Django 5.0.2 on 2024-12-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_gramaje_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidacorporal',
            name='altura',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='fecha_medicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='peso',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='porcentaje_grasa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
