# Generated by Django 5.0.2 on 2024-12-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_medidacorporal_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='static/gym/fotos/cliente.png', null=True, upload_to='static/gym/fotos/'),
        ),
    ]
