# Generated by Django 5.0.2 on 2024-12-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_cliente_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
